version: '3'
services:
  php:
    image: php:7.4-fpm
    volumes:
        - ./nginx/html:/usr/share/nginx/html
    networks:
     - php-nginx

  nginx:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./nginx/html:/usr/share/nginx/html
        - ./nginx/var/www:/var/www
        - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
     - php-nginx

  node:
    image: node:10.15-alpine
    volumes:
        - ./nginx/html:/var/www/html
    tty: true
    ports:
        - "3000:3000"
    networks:
      - php-nginx

networks:
  php-nginx:
    driver: "bridge"